version: '3'
services:
        python3:
                build: .
                container_name: 'rdpg'
                working_dir: '/app'
                tty: true
                environment:
                        - DISPLAY=$DISPLAY
                        - NVIDIA_DRIVER_CAPABILITIES=compute,utility,graphics
                volumes:
                        - ./src:/app/src
                        - /tmp/.X11-unix:/tmp/.X11-unix
                ports:
                        - 6006:6006
                deploy:
                        resources:
                                reservations:
                                        devices:
                                                - capabilities: [gpu]
